### PR TITLE
Show lastmod date on posts

### PR DESCRIPTION
**Pull request by luanalatte**

### CODE REVIEW

**Review by 526avijitgupta — COMMENTED** [review]
@luanalatte Thanks for submitting the PR. I like the idea of showing last modified date. However, I wanted to see how it looks visually on the page. Could you please share a screenshot?

**Comment by luanalatte** [comment]
here it is on my site! https://luanalatte.gitlab.io/posts/doas-as-sudo/

**Review by 526avijitgupta — APPROVED** [review]
LGTM!

**Comment by 526avijitgupta** [comment]
@yashmehrotra Please review and merge if it looks good to you

**Comment by yashmehrotra** [comment]
Thanks for the PR @luanalatte

**Pull request merged**
